Metrics/AbcSize:
  Max: 19

Metrics/ClassLength:
  Max: 172

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/MethodLength:
  Max: 15

Metrics/ModuleLength:
  Max: 150

Metrics/LineLength:
  Max: 110

AllCops:
  Exclude:
    - 'test/dummy/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.3

Style/Encoding:
  EnforcedStyle: when_needed
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/ClassAndModuleChildren:
  Description: 'Checks style of children classes and modules.'
  Enabled: false
